### ISSUE TITLE
running a demo of ei

### ISSUE THREAD

**Issue by PolStats** [iqss-research/ei#19]
I run the code below, and I get the output below. This is using the sample data provided with the package. Any advice would be greatly appreciated.

formula <- t ~ x
dbuf <- ei(formula = formula, total = "n", data = lavoteall)

formula <- t ~ x
> dbuf <- ei(formula = formula, total = "n", data = lavoteall)
ℹ Maximizing likelihood
Error: `ei.estimate()` did not converge. Try a different value of `erho`.
Run `rlang::last_error()` to see where the error occurred.
x Running 2x2 ei [212ms]

**Comment by Shusei-E** [comment]
Does this work? [This page](https://iqss-research.github.io/ei/articles/ei-2x2.html) has more details!
```r
library(ei)
data(matproii)
formula <- t ~ x 
dbuf <- ei(formula = formula, total = "n", data = matproii)
```

**Comment by PolStats** [comment]
Yes, the code you show works.

Sincerely,
Brad Lockerbie

Brad Lockerbie
Professor
Department of Political Science
A-103 Brewster Building
Mailstop 564
East Carolina University
Greenville, NC 27858

252-328-1066<tel://252-328-1066> (office)
Bradlockerbie.com


On Mar 3, 2022, 11:11 PM -0500, Shusei ***@***.***>, wrote:
This email originated from outside ECU.


Does this work? This page<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fiqss-research.github.io%2Fei%2Farticles%2Fei-2x2.html&data=04%7C01%7Clockerbieb%40ecu.edu%7Ce5283a35d6444a695abc08d9fd951071%7C17143cbb385c4c45a36ac65b72e3eae8%7C0%7C0%7C637819638969957686%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AHL4LcByqVZEuaVq8VrZ3B5vt6WcbwXyw1XeN0SbyNA%3D&reserved=0> has more details!

library(ei)
data(matproii)
formula <- t ~ x
dbuf <- ei(formula = formula, total = "n", data = matproii)

—
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fiqss-research%2Fei%2Fissues%2F19%23issuecomment-1058808650&data=04%7C01%7Clockerbieb%40ecu.edu%7Ce5283a35d6444a695abc08d9fd951071%7C17143cbb385c4c45a36ac65b72e3eae8%7C0%7C0%7C637819638969957686%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eu3ij7QOFc46of4S%2BhCev6%2FxXpmVS3944uQ127PD0QI%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXFSLQNBXFI7FCTQ5GX6AC3U6GEPHANCNFSM5P3ZBZWQ&data=04%7C01%7Clockerbieb%40ecu.edu%7Ce5283a35d6444a695abc08d9fd951071%7C17143cbb385c4c45a36ac65b72e3eae8%7C0%7C0%7C637819638969957686%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tVTi3dpfI7xLY7KsXe82Qzau6j1MdprluBURnbeoEtk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Clockerbieb%40ecu.edu%7Ce5283a35d6444a695abc08d9fd951071%7C17143cbb385c4c45a36ac65b72e3eae8%7C0%7C0%7C637819638969957686%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=58T4HeAHRMp2qeyVThnQvysWL6bdIyQqLhrz8GcoSQM%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Clockerbieb%40ecu.edu%7Ce5283a35d6444a695abc08d9fd951071%7C17143cbb385c4c45a36ac65b72e3eae8%7C0%7C0%7C637819638969957686%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yqkSKujPsM6QxxqnMI%2BkFz0o3MBwgpWx1V6mSlEBdPM%3D&reserved=0>.

**Comment by PolStats** [comment]
I still don't understand why one example works but the other doesn't.
